apiVersion: v1
kind: Service
metadata:
  name: workout-planner-service
spec:
  type: NodePort
  selector:
    app: workout-planner
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002
