apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout-planner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workout-planner
  template:
    metadata:
      labels:
        app: workout-planner
    spec:
      containers:
        - name: workout-planner
          image: aboubakar940/workout-planner:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://mongodb-service:27017/ma-db
