name: 🚀 Deploy Kubernetes via Terraform (Destroy puis Apply)

on:
  push:
    branches:
      - main

jobs:
  deploy-terraform:
    runs-on: self-hosted

    env:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Installer Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.4"

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Destroy
        working-directory: terraform
        run: terraform destroy -auto-approve

      - name: Terraform Apply 
        working-directory: terraform
        run: terraform apply -auto-approve
