name: 🚀 Deploy Kubernetes via Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy-terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Installer Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.4"

      - name: Déployer avec Terraform
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve
